# Generated by Django 2.2 on 2020-12-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myrsa2', '0002_auto_20201229_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbOfEnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='app_id')),
                ('app_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='app_secret')),
                ('plat_pub_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='平台公钥')),
                ('ent_pub_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='企业公钥')),
                ('ent_pri_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='企业私钥')),
                ('ent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业名字')),
                ('enc_alg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tbofent', to='myrsa2.EncryptionAlgorithm', verbose_name='加密算法')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbofent', to='myrsa2.Enterprise')),
            ],
            options={
                'db_table': 'table_of_enterprise',
            },
        ),
    ]
