# Generated by Django 3.1.7 on 2021-03-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_VX',
            fields=[
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', unique=True)),
                ('openid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_vx',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='openid',
        ),
    ]
