# Generated by Django 2.2 on 2020-12-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='book',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='hero',
        ),
    ]
