# Generated by Django 2.2 on 2020-12-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_alg', models.CharField(max_length=10, verbose_name='算法名')),
            ],
            options={
                'db_table': 'tb_encrypt_algorithm',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业名字')),
            ],
            options={
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='app_id')),
                ('app_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='app_secret')),
                ('plat_pri_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='平台私钥')),
                ('plat_pub_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='平台公钥')),
                ('ent_pub_key', models.CharField(blank=True, max_length=5000, null=True, verbose_name='企业公钥')),
                ('ent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业名字')),
                ('enc_alg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encryptionalgorithm', to='myrsa2.EncryptionAlgorithm', verbose_name='加密算法')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='myrsa2.Enterprise')),
            ],
            options={
                'db_table': 'app',
            },
        ),
    ]
