# Generated by Django 2.2 on 2020-12-29 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrsa2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='enc_alg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app', to='myrsa2.EncryptionAlgorithm', verbose_name='加密算法'),
        ),
        migrations.AlterField(
            model_name='app',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='myrsa2.Enterprise'),
        ),
    ]
